server:
  port: 8080

spring:
  profiles:
    active: dal, web, config, image
  main:
    allow-circular-references: true
  mvc:
    async:
      request-timeout: 3000

database:
  name: forum

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true